In [1]:
import tensorflow as tf
import numpy as np

/Users/nishithranjanbiswas/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
tensor = tf.constant([[1,2],[3,4]])

2024-02-11 11:02:51.572076: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-02-11 11:02:51.572138: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-02-11 11:02:51.572154: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-02-11 11:02:51.572565: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-11 11:02:51.573087: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [6]:
tensor.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [7]:
tensor + 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7]], dtype=int32)>

In [8]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [9]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [13]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

# Dot Product between tensor

In [14]:
tensor1 = np.square(tensor)

In [15]:
tensor,tensor1

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 array([[ 1,  4],
        [ 9, 16]], dtype=int32))

In [16]:
np.dot(tensor,tensor1)

array([[19, 36],
       [39, 76]], dtype=int32)