# String in Tensorflow

In [1]:
import tensorflow as tf
import numpy as np

/Users/nishithranjanbiswas/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
tf_string = tf.constant('Nishith')

2024-02-11 11:19:21.624928: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-02-11 11:19:21.625006: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-02-11 11:19:21.625024: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-02-11 11:19:21.625474: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-11 11:19:21.626035: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Nishith'>

In [4]:
tf_string.shape

TensorShape([])

In [5]:
tf_string.numpy()

b'Nishith'

In [6]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [7]:
tf.strings.unicode_decode(tf_string,'UTF8')

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 78, 105, 115, 104, 105, 116, 104], dtype=int32)>

# Array of strings

In [8]:
str_array = tf.constant(['Nishith','AI','Tensors','DeepL'])

In [9]:
str_array.shape

TensorShape([4])