In [1]:
import tensorflow as tf
import numpy as np

/Users/nishithranjanbiswas/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
tensor_c = tf.constant([[12,13],[10,11]])

2024-02-11 10:04:00.818512: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-02-11 10:04:00.818614: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-02-11 10:04:00.818635: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-02-11 10:04:00.819133: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-02-11 10:04:00.819763: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
tensor_c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 13],
       [10, 11]], dtype=int32)>

In [5]:
tensor_c.shape

TensorShape([2, 2])

In [7]:
tensor_c.numpy()

array([[12, 13],
       [10, 11]], dtype=int32)

In [8]:
nparray = np.array([[1,3],[5,7]])

In [9]:
np_tensor = tf.constant(nparray)

In [10]:
np_tensor

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 3],
       [5, 7]])>

In [12]:
tensor_var = tf.Variable([[12,55,2],[14,56,77]])

In [13]:
tensor_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[12, 55,  2],
       [14, 56, 77]], dtype=int32)>

In [14]:
tensor_var.numpy

<bound method BaseResourceVariable.numpy of <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[12, 55,  2],
       [14, 56, 77]], dtype=int32)>>

In [16]:
tensor_var.shape

TensorShape([2, 3])

In [17]:
tensor_var[1,1].assign(9)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[12, 55,  2],
       [14,  9, 77]], dtype=int32)>

In [18]:
tensor_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[12, 55,  2],
       [14,  9, 77]], dtype=int32)>